### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by hardcodet** [MisterJimson/Geolocator.FusedLocationProvider#1]
Hi there

I came across your repo through the thread on James Montemagno's Geolocator plugin - thanks for sharing this! Just a quick question since you mentioned there that this needs some love here - is this production ready now, or wouldn't your recommend it for production at this point?

**Comment by MisterJimson** [comment]
I use it in production and it works fine :)

It could use a bit of work, but it works better than trying to manage the providers yourself.

**Comment by hardcodet** [comment]
Thanks for the quick reply - I'll give it a spin then :)
